## configure port and context path
logging:
  level:
    root: info
# -----------------------------sql sharding-------------------------------------------------
spring:
  pid:
    file: '/var/run/@project.name@.pid'
  shardingsphere:
    datasource:
      names: ds0master
      ds0master:
        jdbc-url: jdbc:mysql://127.0.0.1:7328/jvfast?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
        username: ENC(MOJAVmMYz5sp3pl1b7b6qGzu/wC9MzNA)
        password: ENC(naAtUM7Ck1WvuXqt+c+eU1Md5amr0wk1)
    # 分库分表
    sharding:
      # 读写分离
      master-slave-rules:
        ds0:
          master-data-source-name: ds0master
          slave-data-source-names: ds0master
      # 不分库分表的数据源指定
      default-data-source-name: ds0
      # 分表
    #      tables:
    #        # 对默认用户表进行分表
    #        sys_user:
    #          actual-data-nodes: ds0.sys_user${0..1}
    #          table-strategy:
    #            inline:
    #              sharding-column: id
    #              algorithm-expression: sys_user${id % 3}
    #          key-generator:
    #            column: id
    #            type: SNOWFLAKE
  # redis 配置
  redis:
    host: 127.0.0.1
    port: 2963
    database: 9
    password: ENC(rKUjfJSsHOXP94RSjB4QyGrMnMLcK5hLY7v8wAvpHPc0fZrqW6BO84TXPrGJ2LvN)
    ssl: false
# -----------------------------Redis-------------------------------------------------.
# jvfast settings
jvfast:
  demo-enabled: true
  # encrypt
  encrypt:
    enabled: false
    secret-key: b2c17b46e2b13s5392aab5a82869856c
  # jwt
  shiro:
    jwt:
      secret-key: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  # 微信配置
  wx:
    mp:
      # gmail邮箱账号
      configs:
        - name: 胡萝卜网
          appId: wx408a9a0cbefabc91
          secret: 646174fda48d93504ca9423a032a26fd
          token: zxtest2gbyb45o0a1al
          aesKey: XGgHD4KN28p9QEigVYIDCM56UmPpxHe9rA6FMmzjFtM
  # oss存储配置
  oss:
    type: aliyun
    aliyun:
      endpoint: oss-cn-hangzhou.aliyuncs.com
      access-key-id: ENC(hjktw3GR28leOinLKcNFi5OfgAmEz4pb6efu36n1AlHg/ND7zoHtyA==)
      access-key-secret: ENC(VP6ocWzc6z2MrmThSQfKB88JjgQyKBqKUP52nZ7kXIJWMniO6CY9ag==)
      bucket-name: yanzhi-bucket
      domain: https://res.yitieyilu.com
      prefix: test
  # 短信服务配置
  sms:
    type: aliyun
    expired-seconds: 60
    aliyun:
      access-key-id: ENC(K9q0P2HLvCisrgSSlEZzj2HUYyKrLpnQ8h0O9b5artS2ljGWDQNY5A==)
      access-key-secret: ENC(hIYA17G9uVZNpG9rGLTzhHLqlk27DArOGH+3qknig+RWXo4p536g1A==)
      sign-name: 眼值科技
